apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth:xxx
          imagePullPolicy: Never
          resources:
            requests:
              memory: "300Mi"
            limits:
              memory: "500Mi"
          ports:
            - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
    - name: http
      protocol: "TCP"
      port: 8081
      targetPort: 81
